<template>
  <div class="ui-page ui-page--wide room">
    <div v-if="loading" class="ui-card ui-card__body">
      <div class="ui-skeleton" style="height: 22px; width: 40%; margin-bottom: 12px"></div>
      <div class="ui-skeleton" style="height: 280px"></div>
    </div>

    <div v-else-if="error" class="ui-card">
      <div class="ui-empty">
        <div class="ui-empty__icon"><i class="fa-regular fa-calendar-xmark"></i></div>
        <h3>{{ error }}</h3>
        <p>The meeting may have been deleted, or you don't have access to it.</p>
        <router-link to="/meetings" class="ui-btn ui-btn--primary" style="margin-top: 12px"><i class="fa-solid fa-arrow-left"></i> Back to meetings</router-link>
      </div>
    </div>

    <template v-else-if="meeting">
      <header class="ui-page-head">
        <div class="head-main">
          <router-link to="/meetings" class="back"><i class="fa-solid fa-arrow-left"></i> Meetings</router-link>
          <h1>{{ meeting.title }}</h1>
          <p class="head-meta">
            <span><i class="fa-regular fa-clock"></i> {{ range }}</span>
            <span class="ui-badge" :class="`ui-badge--${status.cls}`">{{ status.label }}</span>
            <span v-if="phase === 'in'" class="live"><span class="dot"></span> {{ elapsed }}</span>
          </p>
          <div v-if="(meeting.participants || []).length" class="head-people" :title="meeting.participants.map((p) => p.name || p.email).join(', ')">
            <span v-for="p in meeting.participants.slice(0, 6)" :key="p.email" class="avatar sm">{{ initials(p.name || p.email) }}</span>
            <span class="muted small">{{ participantsLabel }}</span>
          </div>
        </div>
        <div class="ui-actions">
          <button v-if="meeting.join_url" class="ui-btn ui-btn--sm" @click="copyLink"><i class="fa-regular fa-copy"></i> Copy invite link</button>
          <router-link to="/video-call" class="ui-btn ui-btn--sm"><i class="fa-solid fa-people-group"></i> Open video call</router-link>
        </div>
      </header>

      <div v-if="meeting.status === 'cancelled'" class="ui-alert ui-alert--danger mb">
        <i class="fa-regular fa-calendar-xmark"></i><span>This meeting was cancelled. You can still view any saved transcript.</span>
      </div>
      <div v-else-if="meeting.location_type === 'external' && meeting.join_url && phase !== 'done'" class="ui-alert mb">
        <i class="fa-solid fa-link"></i>
        <span>This call happens on an external service. Open it in a new tab, and use this page for live transcription and notes. <a :href="meeting.join_url" target="_blank" rel="noopener">Open meeting link</a></span>
      </div>

      <!-- ============== DONE / SUMMARY ============== -->
      <section v-if="phase === 'done' && saved" class="ui-card">
        <div class="ui-card__head done-head">
          <h2><i class="fa-solid fa-circle-check ok"></i> Transcript & summary saved</h2>
          <div class="ui-actions">
            <button class="ui-btn ui-btn--primary" :disabled="downloading" @click="downloadTxt"><i :class="downloading ? 'fa-solid fa-circle-notch fa-spin' : 'fa-solid fa-file-arrow-down'"></i> Download transcript (.txt)</button>
            <button v-if="meeting.status !== 'cancelled'" class="ui-btn" @click="resume"><i class="fa-solid fa-microphone-lines"></i> Continue recording</button>
          </div>
        </div>
        <div class="ui-card__body summary-body">
          <div>
            <h3>Summary</h3>
            <p class="summary">{{ saved.summary }}</p>
            <p class="muted small">Generated by {{ saved.summary_source === 'anthropic' ? 'Claude' : 'the built-in summariser (offline)' }} · {{ fmtDateTime(saved.updated_at) }}</p>
          </div>
          <div>
            <h3>Key decisions</h3>
            <ul v-if="saved.key_decisions && saved.key_decisions.length" class="bullets">
              <li v-for="(d, i) in saved.key_decisions" :key="i">{{ d }}</li>
            </ul>
            <p v-else class="muted small">None recorded.</p>
            <h3>Action items</h3>
            <ul v-if="saved.action_items && saved.action_items.length" class="actions-list">
              <li v-for="(a, i) in saved.action_items" :key="i">
                <i class="fa-regular fa-square-check"></i>
                <span>{{ a.text }}<small v-if="a.owner || a.due" class="muted d-block"><span v-if="a.owner">Owner: {{ a.owner }}</span><span v-if="a.owner && a.due"> · </span><span v-if="a.due">Due: {{ a.due }}</span></small></span>
              </li>
            </ul>
            <p v-else class="muted small">None recorded.</p>
          </div>
        </div>
        <div class="ui-card__body">
          <details class="full">
            <summary>Full transcript</summary>
            <pre>{{ saved.text || '(no spoken transcript — notes only)' }}</pre>
            <template v-if="saved.notes"><h4>Notes</h4><pre>{{ saved.notes }}</pre></template>
          </details>
          <div class="done-foot">
            <router-link :to="`/meetings?open=${meeting.id}`" class="ui-btn"><i class="fa-regular fa-calendar"></i> View meeting</router-link>
            <router-link to="/meetings" class="ui-btn ui-btn--ghost">Back to meetings</router-link>
          </div>
        </div>
      </section>

      <!-- ============== LOBBY + CALL ============== -->
      <div v-else class="grid" :class="{ 'is-in': phase === 'in' }">
        <section class="ui-card stage-wrap">
          <div class="stage" :class="{ 'has-video': hasVideo && camOn }">
            <video v-show="hasVideo && camOn" ref="video" class="video" autoplay playsinline muted></video>
            <div v-if="!(hasVideo && camOn)" class="stage__placeholder">
              <span class="avatar xl">{{ initials(me.name || 'You') }}</span>
              <span v-if="mediaState === 'requesting'" class="muted"><i class="fa-solid fa-circle-notch fa-spin"></i> Starting camera…</span>
              <span v-else-if="hasVideo && !camOn" class="muted">Camera is off</span>
              <span v-else-if="mediaState === 'ready' && !hasVideo" class="muted">No camera — audio only</span>
            </div>
            <span class="stage__name">{{ me.name || 'You' }}<i v-if="!micOn || !hasAudio" class="fa-solid fa-microphone-slash"></i></span>
            <span v-if="phase === 'in' && recognizing" class="stage__rec"><span class="dot"></span> Transcribing</span>
          </div>

          <div v-if="mediaError" class="ui-alert ui-alert--warning media-alert" role="status">
            <i class="fa-solid fa-video-slash"></i>
            <span>{{ mediaError }} <a v-if="mediaState !== 'unsupported'" href="#" @click.prevent="startMedia">Try again</a></span>
          </div>

          <div class="controls">
            <button class="ctl" :class="{ 'is-off': !micOn || !hasAudio }" :disabled="!hasAudio" :aria-pressed="!micOn" :title="!hasAudio ? 'No microphone' : micOn ? 'Mute' : 'Unmute'" @click="toggleMic">
              <i :class="micOn && hasAudio ? 'fa-solid fa-microphone' : 'fa-solid fa-microphone-slash'"></i><span>{{ micOn && hasAudio ? 'Mute' : 'Unmute' }}</span>
            </button>
            <button class="ctl" :class="{ 'is-off': !camOn || !hasVideo }" :disabled="!hasVideo" :aria-pressed="!camOn" :title="!hasVideo ? 'No camera' : camOn ? 'Turn camera off' : 'Turn camera on'" @click="toggleCam">
              <i :class="camOn && hasVideo ? 'fa-solid fa-video' : 'fa-solid fa-video-slash'"></i><span>{{ camOn && hasVideo ? 'Camera' : 'Camera off' }}</span>
            </button>
            <template v-if="phase === 'lobby'">
              <button class="ui-btn ui-btn--primary join-btn" :disabled="meeting.status === 'cancelled'" @click="join"><i class="fa-solid fa-right-to-bracket"></i> Join now</button>
            </template>
            <template v-else>
              <button v-if="speechSupported" class="ctl" :class="{ 'is-on': recognizing }" :aria-pressed="wantTranscribe" @click="toggleTranscription">
                <i :class="wantTranscribe ? 'fa-solid fa-stop' : 'fa-solid fa-closed-captioning'"></i><span>{{ wantTranscribe ? 'Stop transcript' : 'Transcribe' }}</span>
              </button>
              <button class="ctl ctl--danger" @click="leave"><i class="fa-solid fa-phone-slash"></i><span>Leave</span></button>
              <button class="ui-btn ui-btn--success end-btn" :disabled="saving" @click="endAndSave"><i :class="saving ? 'fa-solid fa-circle-notch fa-spin' : 'fa-solid fa-floppy-disk'"></i> {{ saving ? 'Saving…' : 'End & save' }}</button>
            </template>
          </div>
        </section>

        <!-- Lobby side panel -->
        <aside v-if="phase === 'lobby'" class="ui-card side">
          <div class="ui-card__head"><h2>Ready to join?</h2></div>
          <div class="ui-card__body lobby-info">
            <p class="muted">Check your camera and microphone, then join. Once in, turn on live transcription — the transcript and notes are saved with an automatic summary when you click <strong>End &amp; save</strong>.</p>
            <dl class="facts">
              <div><dt>When</dt><dd>{{ range }}</dd></div>
              <div><dt>Where</dt><dd>{{ where }}</dd></div>
              <div v-if="meeting.organizer_name"><dt>Organizer</dt><dd>{{ meeting.organizer_name }}</dd></div>
              <div v-if="meeting.description"><dt>Agenda</dt><dd class="pre">{{ meeting.description }}</dd></div>
            </dl>
            <label class="ui-field">
              <span>Transcription language</span>
              <select v-model="lang" class="ui-select">
                <option v-for="l in languages" :key="l.code" :value="l.code">{{ l.label }}</option>
              </select>
            </label>
            <p v-if="!speechSupported" class="ui-hint"><i class="fa-solid fa-circle-info"></i> Live transcription isn't supported in this browser (try Chrome or Edge). You can type or paste the transcript during the meeting.</p>
            <div v-if="hasDraft" class="ui-alert">
              <i class="fa-solid fa-clock-rotate-left"></i><span>An unsaved transcript draft from earlier was restored — join to continue it.</span>
            </div>
            <div v-if="saved" class="ui-alert ui-alert--success">
              <i class="fa-solid fa-file-lines"></i>
              <span>A transcript is already saved. <a href="#" @click.prevent="phase = 'done'">View summary</a> · <a href="#" @click.prevent="downloadTxt">Download .txt</a></span>
            </div>
          </div>
        </aside>

        <!-- In-call side panel -->
        <aside v-else class="ui-card side">
          <div class="ui-card__head side-head">
            <h2>Live transcript</h2>
            <select v-model="lang" class="ui-select lang" aria-label="Transcription language" @change="onLangChange">
              <option v-for="l in languages" :key="l.code" :value="l.code">{{ l.label }}</option>
            </select>
          </div>
          <div class="ui-card__body side-body">
            <div v-if="!speechSupported" class="ui-alert ui-alert--warning">
              <i class="fa-solid fa-circle-info"></i><span>Live transcription isn't available in this browser. Type or paste the transcript below — it's summarised when you save.</span>
            </div>
            <div v-else-if="recError" class="ui-alert ui-alert--warning">
              <i class="fa-solid fa-microphone-slash"></i><span>{{ recError }}</span>
            </div>
            <div v-else-if="speechSupported && !wantTranscribe && !segments.length && !editMode" class="ui-alert">
              <i class="fa-solid fa-closed-captioning"></i><span>Transcription is off. <a href="#" @click.prevent="toggleTranscription">Start transcribing</a> or <a href="#" @click.prevent="enterEdit">type it manually</a>.</span>
            </div>
            <div v-else-if="wantTranscribe && !micOn" class="ui-alert">
              <i class="fa-solid fa-microphone-slash"></i><span>You're muted — transcription is paused.</span>
            </div>

            <div class="t-toolbar">
              <span class="muted small">{{ wordCount }} words</span>
              <button v-if="speechSupported" class="ui-btn ui-btn--ghost ui-btn--sm" @click="editMode ? (editMode = false) : enterEdit()"><i :class="editMode ? 'fa-solid fa-list' : 'fa-regular fa-pen-to-square'"></i> {{ editMode ? 'Live view' : 'Edit' }}</button>
            </div>

            <textarea v-if="editMode || !speechSupported" v-model="editText" class="ui-textarea transcript-edit" rows="10" placeholder="[10:00:00] You: Paste or type the transcript here…" aria-label="Transcript"></textarea>
            <div v-else ref="tbox" class="transcript" aria-live="polite">
              <p v-if="!segments.length && !interim" class="muted small empty">{{ wantTranscribe ? 'Listening… start speaking.' : 'Nothing transcribed yet.' }}</p>
              <p v-for="(s, i) in segments" :key="i" class="seg">
                <span class="seg__ts">{{ s.ts }}</span><strong>{{ s.speaker }}</strong> {{ s.text }}
                <button class="seg__del" :aria-label="`Remove line ${i + 1}`" title="Remove line" @click="segments.splice(i, 1)"><i class="fa-solid fa-xmark"></i></button>
              </p>
              <p v-if="interim" class="seg interim"><span class="seg__ts">{{ nowTs() }}</span><strong>You</strong> {{ interim }}</p>
            </div>

            <label class="ui-field notes">
              <span>Notes</span>
              <textarea v-model="notes" class="ui-textarea" rows="4" placeholder="Decisions, follow-ups, anything worth remembering…"></textarea>
            </label>
          </div>
        </aside>
      </div>
    </template>
  </div>
</template>

<script>
import { markRaw } from 'vue'
import { apiErrorMessage } from '@/services/api'
import { toast } from '@/composables/useToast'
import { confirmDialog } from '@/composables/useConfirm'
import { formatDateTime } from '@/utils/format'
import { meetingsApi, fmtRange, displayStatus, locationLabel, initials } from '@/services/meetings'

const LANGUAGES = [
  { code: 'en-AU', label: 'English (Australia)' },
  { code: 'en-US', label: 'English (US)' },
  { code: 'en-GB', label: 'English (UK)' },
  { code: 'en-IN', label: 'English (India)' },
  { code: 'en-NZ', label: 'English (New Zealand)' },
  { code: 'sw-KE', label: 'Kiswahili' },
  { code: 'fr-FR', label: 'Français' },
  { code: 'de-DE', label: 'Deutsch' },
  { code: 'es-ES', label: 'Español' },
  { code: 'it-IT', label: 'Italiano' },
  { code: 'pt-BR', label: 'Português (Brasil)' },
  { code: 'zh-CN', label: '中文 (普通话)' },
  { code: 'ja-JP', label: '日本語' },
  { code: 'hi-IN', label: 'हिन्दी' },
  { code: 'ar-SA', label: 'العربية' },
  { code: 'vi-VN', label: 'Tiếng Việt' }
]

function pad(n) {
  return String(n).padStart(2, '0')
}

function readStore(key) {
  try {
    return JSON.parse(localStorage.getItem(key) || 'null')
  } catch {
    return null
  }
}
function writeStore(key, value) {
  try {
    if (value === null) localStorage.removeItem(key)
    else localStorage.setItem(key, JSON.stringify(value))
  } catch {
    /* storage unavailable */
  }
}

export default {
  name: 'MeetingRoom',
  data() {
    const SR = typeof window !== 'undefined' ? window.SpeechRecognition || window.webkitSpeechRecognition : null
    let lang = 'en-AU'
    try {
      lang = localStorage.getItem('meetings.lang') || (navigator.language && LANGUAGES.some((l) => l.code === navigator.language) ? navigator.language : 'en-AU')
    } catch {
      /* ignore */
    }
    return {
      meeting: null,
      loading: true,
      error: '',
      phase: 'lobby', // lobby | in | done
      // media
      stream: null,
      mediaState: 'idle', // idle | requesting | ready | error | unsupported
      mediaError: '',
      micOn: true,
      camOn: true,
      // transcription
      SR,
      speechSupported: !!SR,
      recognizer: null,
      recognizing: false,
      wantTranscribe: false,
      recError: '',
      lang,
      languages: LANGUAGES,
      segments: [],
      interim: '',
      editMode: !SR,
      editText: '',
      notes: '',
      hasDraft: false,
      // save
      saving: false,
      saved: null,
      downloading: false,
      // misc
      joinedAt: null,
      tick: Date.now(),
      timer: null,
      me: { name: '' },
      draftTimer: null
    }
  },
  computed: {
    id() {
      return this.$route.params.id
    },
    draftKey() {
      return `meetings.draft.${this.id}`
    },
    status() {
      return displayStatus(this.meeting, this.tick)
    },
    range() {
      return fmtRange(this.meeting)
    },
    where() {
      if (this.meeting.location_type === 'physical') return this.meeting.location
      return locationLabel(this.meeting)
    },
    participantsLabel() {
      const n = (this.meeting.participants || []).length
      return `${n} ${n === 1 ? 'participant' : 'participants'}`
    },
    hasVideo() {
      return !!this.stream && this.stream.getVideoTracks().length > 0
    },
    hasAudio() {
      return !!this.stream && this.stream.getAudioTracks().length > 0
    },
    elapsed() {
      if (!this.joinedAt) return '00:00'
      const s = Math.max(0, Math.floor((this.tick - this.joinedAt) / 1000))
      const h = Math.floor(s / 3600)
      return (h ? `${h}:` : '') + `${pad(Math.floor((s % 3600) / 60))}:${pad(s % 60)}`
    },
    liveText() {
      return this.segments.map((s) => `[${s.ts}] ${s.speaker}: ${s.text}`).join('\n')
    },
    transcriptText() {
      return (this.editMode || !this.speechSupported ? this.editText : this.liveText).trim()
    },
    wordCount() {
      const t = this.transcriptText.replace(/\[\d{2}:\d{2}:\d{2}\]\s*\w+:/g, ' ')
      return (t.match(/\S+/g) || []).length
    }
  },
  watch: {
    segments: {
      deep: true,
      handler() {
        this.saveDraftSoon()
        this.scrollTranscript()
      }
    },
    editText() {
      this.saveDraftSoon()
    },
    notes() {
      this.saveDraftSoon()
    },
    lang(v) {
      try {
        localStorage.setItem('meetings.lang', v)
      } catch {
        /* ignore */
      }
    },
    phase() {
      this.$nextTick(this.attachVideo)
    }
  },
  async mounted() {
    try {
      const u = JSON.parse(localStorage.getItem('current_user') || 'null')
      if (u) this.me.name = `${u.first_name || ''} ${u.last_name || ''}`.trim() || u.email || ''
    } catch {
      /* ignore */
    }
    this.timer = setInterval(() => (this.tick = Date.now()), 1000)
    window.addEventListener('beforeunload', this.onBeforeUnload)
    await this.load()
    if (this.meeting && this.meeting.status !== 'cancelled' && this.phase === 'lobby') this.startMedia()
  },
  beforeUnmount() {
    this.destroyed = true
    clearInterval(this.timer)
    clearTimeout(this.draftTimer)
    window.removeEventListener('beforeunload', this.onBeforeUnload)
    this.stopTranscription()
    this.stopMedia()
  },
  methods: {
    initials,
    fmtDateTime: formatDateTime,
    nowTs() {
      const d = new Date()
      return `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
    },
    async load() {
      this.loading = true
      try {
        const { meeting } = await meetingsApi.get(this.id)
        this.meeting = meeting
        if (meeting.has_transcript) {
          try {
            this.saved = await meetingsApi.getTranscript(this.id)
          } catch {
            this.saved = null
          }
        }
        const draft = readStore(this.draftKey)
        if (draft && (draft.segments?.length || draft.editText || draft.notes)) {
          this.segments = draft.segments || []
          this.editText = draft.editText || ''
          this.notes = draft.notes || ''
          this.editMode = !this.speechSupported || !!draft.editMode
          this.hasDraft = true
        } else if (this.saved && (meeting.status === 'completed' || meeting.status === 'cancelled')) {
          this.phase = 'done'
        }
      } catch (err) {
        this.error = err?.response?.status === 404 ? 'Meeting not found' : apiErrorMessage(err, 'Could not load the meeting')
      } finally {
        this.loading = false
      }
    },

    // ---------------- media ----------------
    mediaMessage(err) {
      const name = err?.name || ''
      if (name === 'NotAllowedError' || name === 'SecurityError' || name === 'PermissionDeniedError') return 'Camera and microphone access was blocked. Allow access in your browser (address bar → site permissions), then try again. You can still join, transcribe by typing, and take notes.'
      if (name === 'NotFoundError' || name === 'DevicesNotFoundError' || name === 'OverconstrainedError') return 'No camera or microphone was found on this device. You can still join and take notes or paste a transcript.'
      if (name === 'NotReadableError' || name === 'TrackStartError' || name === 'AbortError') return 'Your camera or microphone is being used by another app. Close it and try again.'
      return 'Could not start your camera or microphone. You can still join without them.'
    },
    async startMedia() {
      this.mediaError = ''
      if (!navigator.mediaDevices || typeof navigator.mediaDevices.getUserMedia !== 'function') {
        this.mediaState = 'unsupported'
        this.mediaError = 'Camera and microphone need a secure (HTTPS) connection and a supported browser. You can still join and take notes.'
        return
      }
      this.stopMedia()
      this.mediaState = 'requesting'
      let stream = null
      let firstErr = null
      try {
        stream = await navigator.mediaDevices.getUserMedia({ video: { width: { ideal: 1280 }, height: { ideal: 720 } }, audio: { echoCancellation: true, noiseSuppression: true } })
      } catch (err) {
        firstErr = err
        // Try whichever device exists on its own (e.g. a laptop without a webcam).
        if (err?.name !== 'NotAllowedError' && err?.name !== 'SecurityError') {
          for (const c of [{ audio: true }, { video: true }]) {
            try {
              stream = await navigator.mediaDevices.getUserMedia(c)
              break
            } catch {
              /* try next */
            }
          }
        }
      }
      if (this.destroyed) {
        stream?.getTracks().forEach((t) => t.stop())
        return
      }
      if (!stream) {
        this.mediaState = 'error'
        this.mediaError = this.mediaMessage(firstErr)
        return
      }
      this.stream = markRaw(stream)
      this.mediaState = 'ready'
      if (firstErr) this.mediaError = stream.getVideoTracks().length ? 'No microphone was found — joining with camera only.' : 'No camera was found — joining with audio only.'
      stream.getAudioTracks().forEach((t) => (t.enabled = this.micOn))
      stream.getVideoTracks().forEach((t) => (t.enabled = this.camOn))
      this.$nextTick(this.attachVideo)
    },
    attachVideo() {
      const v = this.$refs.video
      if (!v || !this.stream) return
      if (v.srcObject !== this.stream) v.srcObject = this.stream
      const p = v.play && v.play()
      if (p && typeof p.catch === 'function') p.catch(() => {})
    },
    stopMedia() {
      if (this.stream) this.stream.getTracks().forEach((t) => t.stop())
      this.stream = null
      const v = this.$refs.video
      if (v) v.srcObject = null
    },
    toggleMic() {
      this.micOn = !this.micOn
      this.stream?.getAudioTracks().forEach((t) => (t.enabled = this.micOn))
      if (this.phase === 'in' && this.wantTranscribe) {
        if (!this.micOn) this.pauseRecognizer()
        else this.startRecognizer()
      }
    },
    toggleCam() {
      this.camOn = !this.camOn
      this.stream?.getVideoTracks().forEach((t) => (t.enabled = this.camOn))
      if (this.camOn) this.$nextTick(this.attachVideo)
    },

    // ---------------- call ----------------
    join() {
      this.phase = 'in'
      this.joinedAt = Date.now()
      this.hasDraft = false
      if (this.meeting.status === 'scheduled') {
        meetingsApi
          .start(this.meeting.id)
          .then((r) => {
            if (r?.meeting) this.meeting = { ...this.meeting, status: r.meeting.status }
          })
          .catch(() => {})
      }
      if (this.speechSupported && !this.editMode) this.toggleTranscription()
    },
    resume() {
      if (this.saved && !this.segments.length && !this.editText) {
        this.editText = this.saved.text || ''
        this.notes = this.saved.notes || ''
        this.editMode = true
      }
      this.phase = 'lobby'
      this.startMedia()
    },
    async leave() {
      if (this.transcriptText || this.notes.trim()) {
        const ok = await confirmDialog({ title: 'Leave without saving?', message: 'Your transcript and notes stay as a draft on this device. Use "End & save" to save them and create a summary.', confirmText: 'Leave' })
        if (!ok) return
      }
      this.stopTranscription()
      this.stopMedia()
      this.$router.push('/meetings')
    },
    onBeforeUnload(e) {
      if (this.phase === 'in' && (this.transcriptText || this.notes.trim())) {
        this.flushDraft()
        e.preventDefault()
        e.returnValue = ''
      }
    },

    // ---------------- transcription ----------------
    toggleTranscription() {
      if (this.wantTranscribe) {
        this.stopTranscription()
        return
      }
      this.recError = ''
      this.wantTranscribe = true
      if (this.micOn) this.startRecognizer()
    },
    startRecognizer() {
      if (!this.SR || this.recognizing) return
      let rec = this.recognizer
      if (!rec) {
        try {
          rec = new this.SR()
        } catch {
          this.speechSupported = false
          this.editMode = true
          this.wantTranscribe = false
          return
        }
        rec.continuous = true
        rec.interimResults = true
        rec.maxAlternatives = 1
        rec.onstart = () => (this.recognizing = true)
        rec.onresult = (e) => {
          let interim = ''
          for (let i = e.resultIndex; i < e.results.length; i++) {
            const r = e.results[i]
            const text = (r[0]?.transcript || '').trim()
            if (!text) continue
            if (r.isFinal) this.pushSegment(text)
            else interim += (interim ? ' ' : '') + text
          }
          this.interim = interim
        }
        rec.onerror = (e) => {
          const err = e?.error
          if (err === 'no-speech' || err === 'aborted') return
          if (err === 'not-allowed' || err === 'service-not-allowed') this.recError = 'Microphone access for transcription was blocked. Allow the microphone for this site, or type the transcript using Edit.'
          else if (err === 'audio-capture') this.recError = 'No microphone is available for transcription. Type or paste the transcript using Edit.'
          else if (err === 'network') this.recError = 'The speech service could not be reached (it needs an internet connection). You can type the transcript using Edit.'
          else if (err === 'language-not-supported') this.recError = 'That language isn’t supported for live transcription. Pick another language.'
          else this.recError = `Transcription stopped (${err || 'unknown error'}).`
          this.wantTranscribe = false
        }
        rec.onend = () => {
          this.recognizing = false
          if (this.interim) {
            this.pushSegment(this.interim)
            this.interim = ''
          }
          // Chrome ends recognition after silence — restart while it's wanted.
          if (this.wantTranscribe && this.micOn && this.phase === 'in') setTimeout(() => this.startRecognizer(), 300)
        }
        this.recognizer = markRaw(rec)
      }
      rec.lang = this.lang
      try {
        rec.start()
      } catch {
        /* already started */
      }
    },
    pauseRecognizer() {
      try {
        this.recognizer?.stop()
      } catch {
        /* ignore */
      }
    },
    stopTranscription() {
      this.wantTranscribe = false
      if (this.recognizer) {
        try {
          this.recognizer.abort()
        } catch {
          /* ignore */
        }
      }
      if (this.interim) {
        this.pushSegment(this.interim)
        this.interim = ''
      }
      this.recognizing = false
    },
    onLangChange() {
      if (this.recognizing) this.pauseRecognizer() // onend restarts with the new language
    },
    pushSegment(text) {
      const ts = this.nowTs()
      const seg = { ts, speaker: 'You', text: text.charAt(0).toUpperCase() + text.slice(1) }
      this.segments.push(seg)
      if (this.editMode) {
        const line = `[${ts}] You: ${seg.text}`
        this.editText = this.editText && !this.editText.endsWith('\n') ? `${this.editText}\n${line}` : this.editText + line
      }
    },
    enterEdit() {
      if (!this.editText.trim()) this.editText = this.liveText
      this.editMode = true
    },
    scrollTranscript() {
      this.$nextTick(() => {
        const el = this.$refs.tbox
        if (el && el.scrollHeight - el.scrollTop - el.clientHeight < 120) el.scrollTop = el.scrollHeight
      })
    },

    // ---------------- drafts & save ----------------
    saveDraftSoon() {
      clearTimeout(this.draftTimer)
      this.draftTimer = setTimeout(this.flushDraft, 800)
    },
    flushDraft() {
      if (this.phase === 'done') return
      const empty = !this.segments.length && !this.editText.trim() && !this.notes.trim()
      writeStore(this.draftKey, empty ? null : { segments: this.segments, editText: this.editText, notes: this.notes, editMode: this.editMode, savedAt: Date.now() })
    },
    async endAndSave() {
      if (this.interim) {
        this.pushSegment(this.interim)
        this.interim = ''
      }
      const text = this.transcriptText
      const notes = this.notes.trim()
      if (!text && !notes) {
        toast.warning('Nothing to save yet — transcribe, type the transcript or add notes first.')
        return
      }
      const ok = await confirmDialog({ title: 'End the meeting and save?', message: 'The transcript and notes are saved, a summary with decisions and action items is generated, and the meeting is marked completed.', confirmText: 'End & save' })
      if (!ok) return
      this.saving = true
      this.stopTranscription()
      try {
        const res = await meetingsApi.saveTranscript(this.meeting.id, { text, notes, language: this.lang, complete: true })
        this.saved = res.transcript
        if (res.meeting) this.meeting = { ...this.meeting, status: res.meeting.status, has_transcript: true }
        clearTimeout(this.draftTimer)
        writeStore(this.draftKey, null)
        this.segments = []
        this.editText = ''
        this.notes = ''
        this.stopMedia()
        this.phase = 'done'
        toast.success('Transcript saved and summarised')
      } catch (err) {
        toast.error(apiErrorMessage(err, 'Could not save the transcript'))
        this.flushDraft()
      } finally {
        this.saving = false
      }
    },
    async downloadTxt() {
      this.downloading = true
      try {
        await meetingsApi.downloadTranscript(this.meeting)
      } catch (err) {
        toast.error(apiErrorMessage(err, 'Could not download the transcript'))
      } finally {
        this.downloading = false
      }
    },
    async copyLink() {
      try {
        await navigator.clipboard.writeText(this.meeting.join_url)
        toast.success('Invite link copied')
      } catch {
        toast.error('Copy failed — select the link and copy it manually')
      }
    }
  }
}
</script>

<style scoped>
.mb {
  margin-bottom: 16px;
}
.muted {
  color: var(--text-3);
}
.small {
  font-size: 13px;
}
.d-block {
  display: block;
}
.ok {
  color: var(--success);
}
.back {
  display: inline-flex;
  gap: 6px;
  align-items: center;
  color: var(--text-3);
  font-size: 13px;
  text-decoration: none;
  margin-bottom: 6px;
}
.back:hover {
  color: var(--accent);
}
.head-main {
  min-width: 0;
}
.head-main h1 {
  overflow-wrap: anywhere;
}
.head-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 14px;
  align-items: center;
}
.head-people {
  display: flex;
  align-items: center;
  margin-top: 8px;
}
.head-people .avatar + .avatar {
  margin-left: -6px;
}
.head-people .muted {
  margin-left: 10px;
}
.live {
  display: inline-flex;
  gap: 6px;
  align-items: center;
  color: var(--danger);
  font-weight: 600;
  font-variant-numeric: tabular-nums;
}
.dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: var(--danger);
  animation: pulse 1.4s infinite;
}
@keyframes pulse {
  50% {
    opacity: 0.35;
  }
}
.avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  display: grid;
  place-items: center;
  flex-shrink: 0;
  background: var(--accent-soft);
  color: var(--accent);
  font-weight: 700;
  font-size: 12px;
  border: 2px solid var(--surface);
}
.avatar.sm {
  width: 28px;
  height: 28px;
  font-size: 11px;
}
.avatar.xl {
  width: 96px;
  height: 96px;
  font-size: 32px;
}
.grid {
  display: grid;
  grid-template-columns: minmax(0, 1.6fr) minmax(320px, 1fr);
  gap: 16px;
  align-items: start;
}
.stage-wrap {
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.stage {
  position: relative;
  aspect-ratio: 16 / 9;
  border-radius: var(--radius);
  background: var(--bg-subtle);
  border: 1px solid var(--border);
  overflow: hidden;
  display: grid;
  place-items: center;
}
.stage.has-video {
  background: #000;
}
.video {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transform: scaleX(-1);
}
.stage__placeholder {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  text-align: center;
  padding: 16px;
}
.stage__name,
.stage__rec {
  position: absolute;
  bottom: 10px;
  left: 10px;
  padding: 4px 10px;
  border-radius: 999px;
  background: rgba(0, 0, 0, 0.55);
  color: #fff;
  font-size: 12px;
  display: inline-flex;
  gap: 8px;
  align-items: center;
}
.stage__rec {
  left: auto;
  right: 10px;
  top: 10px;
  bottom: auto;
}
.media-alert {
  margin: 0;
}
.controls {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  align-items: center;
  justify-content: center;
}
.ctl {
  font: inherit;
  display: inline-flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  min-width: 76px;
  padding: 8px 10px;
  border-radius: var(--radius);
  border: 1px solid var(--border);
  background: var(--surface-2);
  color: var(--text);
  cursor: pointer;
  font-size: 12px;
}
.ctl i {
  font-size: 16px;
}
.ctl:hover:not(:disabled) {
  background: var(--surface-hover);
}
.ctl:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.ctl.is-off {
  background: var(--danger-soft);
  color: var(--danger);
  border-color: transparent;
}
.ctl.is-on {
  background: var(--accent-soft);
  color: var(--accent);
  border-color: var(--accent);
}
.ctl--danger {
  color: var(--danger);
}
.join-btn,
.end-btn {
  padding-left: 20px;
  padding-right: 20px;
  min-height: 52px;
}
.side-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 8px;
}
.lang {
  width: auto;
  max-width: 190px;
}
.side-body,
.lobby-info {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.lobby-info > p {
  margin: 0;
}
.facts {
  margin: 0;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.facts > div {
  display: grid;
  grid-template-columns: 90px 1fr;
  gap: 8px;
  font-size: 14px;
}
.facts dt {
  color: var(--text-3);
}
.facts dd {
  margin: 0;
  min-width: 0;
  overflow-wrap: anywhere;
}
.pre {
  white-space: pre-wrap;
}
.t-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.transcript {
  height: 320px;
  overflow: auto;
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: var(--surface-2);
  padding: 10px 12px;
}
.transcript .empty {
  margin: 0;
}
.transcript-edit {
  min-height: 320px;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 13px;
}
.seg {
  margin: 0 0 8px;
  font-size: 14px;
  line-height: 1.5;
  position: relative;
  padding-right: 22px;
}
.seg__ts {
  color: var(--text-3);
  font-size: 11px;
  font-variant-numeric: tabular-nums;
  margin-right: 6px;
}
.seg strong {
  color: var(--accent);
  margin-right: 2px;
}
.seg.interim {
  color: var(--text-3);
  font-style: italic;
}
.seg__del {
  position: absolute;
  right: 0;
  top: 0;
  border: 0;
  background: none;
  color: var(--text-3);
  cursor: pointer;
  opacity: 0;
  padding: 2px 4px;
}
.seg:hover .seg__del,
.seg__del:focus-visible {
  opacity: 1;
}
.notes {
  margin: 0;
}
.done-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 10px;
}
.summary-body {
  display: grid;
  grid-template-columns: 1.3fr 1fr;
  gap: 24px;
  border-bottom: 1px solid var(--border);
}
.summary-body h3 {
  font-size: 13px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: var(--text-3);
  margin: 0 0 8px;
}
.summary-body h3 + p,
.summary-body ul + h3,
.summary-body p + h3 {
  margin-top: 16px;
}
.summary {
  line-height: 1.6;
  margin: 0 0 8px;
}
.bullets {
  margin: 0;
  padding-left: 18px;
}
.actions-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.actions-list li {
  display: flex;
  gap: 8px;
}
.actions-list i {
  color: var(--accent);
  margin-top: 3px;
}
.full {
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 8px 12px;
  background: var(--surface-2);
}
.full summary {
  cursor: pointer;
  font-weight: 600;
  font-size: 14px;
}
.full pre {
  white-space: pre-wrap;
  font-family: inherit;
  font-size: 13px;
  max-height: 360px;
  overflow: auto;
  color: var(--text-2);
}
.done-foot {
  display: flex;
  gap: 8px;
  margin-top: 14px;
  flex-wrap: wrap;
}
@media (max-width: 980px) {
  .grid {
    grid-template-columns: 1fr;
  }
  .summary-body {
    grid-template-columns: 1fr;
  }
}
@media (max-width: 520px) {
  .ctl {
    min-width: 0;
    flex: 1 1 0;
    padding: 6px 4px;
  }
  .join-btn,
  .end-btn {
    width: 100%;
  }
  .facts > div {
    grid-template-columns: 1fr;
    gap: 2px;
  }
}
</style>
